const __P = require('./_config.js');
// Layer the movie-subtitle patch onto the CURRENTLY deployed common.dat (keeps
// the earlier text patches) and deploy to both RPCS3 dev_hdd0 and the mirror.
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const HDD = `${__P.HDD}`;
const MIRROR = `${__P.MIRROR}`;
const WORK = `${__P.WORK}`;
const PACK = path.join(WORK, 'pack2');

fs.mkdirSync(PACK, { recursive: true });

// Merge the text/mask manifest with the optional font manifest (font01.dds +
// fontidexu8.tbl extension) so both land in one common.dat pass.  The font
// manifest is kept separate because patch_common.json is regenerated by the
// mask/import tools.
const patchPath = path.join(WORK, 'patch_common.json');
const fontPath = path.join(WORK, 'patch_font.json');
const patches = JSON.parse(fs.readFileSync(patchPath, 'utf8'));
if (fs.existsSync(fontPath)) {
  Object.assign(patches, JSON.parse(fs.readFileSync(fontPath, 'utf8')));
  console.log('merged patch_font.json');
}
const mergedPath = path.join(WORK, 'patch_merged.json');
fs.writeFileSync(mergedPath, JSON.stringify(patches, null, 2));

// Base is the live HDD install when present, otherwise the disc source, so a
// clean checkout can rebuild without a configured RPCS3 profile.
const BASE = `${__P.BASE}`;
execFileSync(process.execPath, [path.join(`${__P.TOOLS}`, 'sntp_pack.js'),
  path.join(BASE, 'common.hed'), path.join(BASE, 'common.dat'),
  mergedPath, PACK], { stdio: 'inherit' });

// Write dist/ first, then the mirror and the live HDD when present
// (see __P.DATA_TARGETS).  --mirror-only keeps the legacy mirror-only behaviour.
const mirrorOnly = process.argv.includes('--mirror-only');
const targets = mirrorOnly ? [MIRROR] : __P.DATA_TARGETS;
for (const dst of targets) {
  fs.mkdirSync(dst, { recursive: true });
  for (const f of ['common.dat', 'common.hed', 'common.siz']) {
    const s = path.join(PACK, f), d = path.join(dst, f);
    if (!fs.existsSync(s)) continue;
    if (fs.existsSync(d)) { try { fs.unlinkSync(d); } catch (e) { /* sandbox may block delete; overwrite in place */ } }
    fs.copyFileSync(s, d);
    console.log('deployed', f, '->', dst, fs.statSync(d).size);
  }
}
console.log('done');